# Generated by Django 4.1.5 on 2023-02-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/loc'),
        ),
    ]
