# Generated by Django 4.1.7 on 2023-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_location_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
