# Generated by Django 4.1.7 on 2023-03-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_reviewrating_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
