# Generated by Django 4.1.2 on 2022-10-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='all_products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='all_products',
            name='proudct_id',
        ),
        migrations.RemoveField(
            model_name='all_products',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='all_products',
            name='user',
        ),
    ]
