# Generated by Django 4.1.2 on 2022-10-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_all_products_image_all_products_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Products',
        ),
    ]
