# Generated by Django 4.1.5 on 2023-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_bike_product_add_info_alter_bike_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_product',
            name='ad_title',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
