# Generated by Django 4.1.7 on 2023-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_house_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_product',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
