# Generated by Django 4.1.7 on 2023-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_type_house_product_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_product',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
