# Generated by Django 4.1.7 on 2023-04-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_rename_house_type_house_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.house_product')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
