# Generated by Django 4.1.7 on 2023-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_interested_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested_product',
            name='interest_status',
            field=models.BooleanField(default=False),
        ),
    ]
