# Generated by Django 4.1.7 on 2023-04-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_interested_product_interest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested_Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_status', models.BooleanField(default=False)),
                ('o_product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.other_product')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interested_Furn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_status', models.BooleanField(default=False)),
                ('f_product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.furn_product')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interested_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_status', models.BooleanField(default=False)),
                ('c_product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.car_product')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interested_Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_status', models.BooleanField(default=False)),
                ('b_product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.bike_product')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
